### ISSUE TITLE
Create Docker image for development server

### ISSUE THREAD

**Issue by johnnyapol** [TornDotSpace/Torn#1]
Easier cross-platform development

**Comment by DamienVesper** [comment]
Currently the game relies on several different frameworks that differ greatly across different platforms. In my fork, I am bringing these all together underneath one hood to streamline the process, and to make it easier to create a Docker build configuration.

**Comment by DamienVesper** [comment]
Done in [ceed64e](https://github.com/TornDotSpace/Torn/tree/ceed64e9c3b32be54a19dbc46f436f2f7908db58).

**Comment by DamienVesper** [comment]
Note: Docker support was removed due to it not being the most optimized image along with the little to no use for it. No need to reopen this issue, but perhaps can be reimplemented if there is demand for it again, whereas currently, there is not.
