### ISSUE TITLE
Re-enable non-english language support in game

### ISSUE THREAD

**Issue by johnnyapol** [TornDotSpace/Torn#11]
https://github.com/TornDotSpace/Torn/commit/dd0ced4e923c49dd347acb4d5a7e1e43425bd9a4

**Comment by 2swap** [comment]
I think a great way to make this much easier would be to instead index an array of integers to get some translation would be to use a dictionary, indexed by english words, which stores the translations of the words. Also, I think it would be a good idea to merge all the translation files into one.

**Comment by 2swap** [comment]
Done, see latest commit. We should remove the currently unsupported languages for the moment, or port them to the new system. I found a vietnamese translator, and I will be doing the mandarin translation with some help from the RPI Chinese mentors :)
