### ISSUE TITLE
Modify the description position for Weapons.

### ISSUE THREAD

**Issue by tardisfromtornspace** [TornDotSpace/Torn#187]
In order not to lose the energy cost description line, not overlapping the weapon description with the weapon's properties, and allowing more space for possible new weapons, taking the idea from Gingyh2o, I think it would be useful to use multiple rows. Here's a possible format to use:

Shop
{Weapons_list here}

Type:  Gun .........| Name of the Weapon goes here.
Range: 250 ........| Description of the Weapon goes here.
Damage: 25 ......|
Energy: 3 ............|
Speed: 50 ...........|
Charge: 0.32 .....|
Ammo: Inf ..........|Use the space above these lines to add  
Rank:  0 ...............|an extensive desc. of the weapon.

**Comment by 2swap** [comment]
This is no longer an issue as far as I know
