### ISSUE TITLE
Confirm Leave Game

### ISSUE THREAD

**Issue by DamienVesper** [TornDotSpace/Torn#189]
Taken from me today, I went down to one life due to the fact that I accidentally pressed Ctrl + W while attacking bots. There should be a document.beforeUnload() message shown through Window.confirm() whether you want to leave the page or not (only when you are not docked at base, if docked at base then just leave the game).

**Comment by johnnyapol** [comment]
Sadly there isn't a really good way to implement this -- showing the prompt only for people to timeout and have to log back in isn't any different than what we have now.
