### ISSUE TITLE
Allow bases to be destroyed

### ISSUE THREAD

**Issue by tardisfromtornspace** [TornDotSpace/Torn#191]
When you kill a turret, you should be able to destroy the base that is protecting. The base would have 10000 HP (it would also regenerate slightly slower than the turret) and it would give 10k xp and 1M money. Once the base is destroyed, it will respawn 30 seconds after in another friendly sector (or just in the same sector in order not to complicate things).

**Comment by 2swap** [comment]
This is complicated, a lot of work, and I don't see it really affecting gameplay much.
