### ISSUE TITLE
Tweaks to ships/Controls and Ideas for ship variants, fusions and other related abilities.

### ISSUE THREAD

**Issue by tardisfromtornspace** [TornDotSpace/Torn#196]
**All ships**: a buff of 0.05 speed. 

All ships should have an **AI autopilot** when pressing P instead of just blocking the controls (you would go forward, but it would avoid black holes and enemy ships until they get at 250 units, the point where it would attack them).

**Option to Self-Destruct by a chat command**, you need to confirm it. If you die by Self-Destruct you get Emo achievement and you only lose 1% of xp, not 2%.

(From D-99) Make it so you have **decks to change your set of weapons, support, or other stuff back**. either save the money on the weapons when changing the deck because it cost, or buy when changing the decks like you buy a deck of the weapons, you can also remove or add the weapons in the deck. 

(From D-99) **Being able to combine 2 accounts xp, money and stats.**

Make **sprites the hitbox for weapons**, NOT a magical circle around the ship

Each ship should have a **base energy level** too, being 100 the minimum, and from rank 10 each ship would have 10 extra energy units (so rank 20 would have 200 energy).
_REASON: More realistic._

An option to have **ship variants** (where some stats are multiplied by 1.25 at the cost of other stats divided by that amount). Those variants would be unlocked when leveling up. Like up and down arrows in the Shop Menu so if you are a ship you could choosee 2 variants with more hull/cargo but less speed or vice-versa (like a Speed R15 variant with 0.4 thrust but 400 hull, or a Heavy R15 variant with 625 hull but 0.256 thrust). In the case of ships with great cargo and low speed (like ranks 12, 17 and 20) those two versions would sacrifice cargo.

**R5**: make Minigun available again to this ship.

**Docking Clamp** (idea from 24sans24): Available to R12 or higher (it's not a slot, it's a passive ability). this allows one person to essentially "dock" inside you if they are 8 ranks below you as long as you have 2000 units of free space (1-4 people. Each one needs additional cargo). By docking in the ship, you essentially use your energy to resupply theirs. having someone docked also means if the big ship is destroyed, that they too will be destroyed. The benefit of docking is that this will increase the energy production of the ship allowing the person to be docked (increasing overall combat ability). Also, when docked you can talk to the person in a purple text labeled [Docked]. Being docked allows the ship with lesser radar to see with the radar of the other ship and both ships could transfer money and ore by a command like /pay (name) *money amount* and /transfer (name) *ore amount*) . 
_REASON: I feel by adding this feature it would make the game more fun to play with friends and would open a more broad perspective into the whole Co-Op. rather than just saying hi to the new players, you could hire them to protect your ship from swarms of bots while attacking a turret._

**R13**: buff HP to 350. _REASON: the rank 13 feels a bit too weak for its size._

**R14**: buff HP to 260. _REASON: the ship is now a bit slower, it should be compensated._ 
Also (from slaine11), as a visual effect, make the tips on R14 an intermitent illuminated glow. _REASON: more realistic_

**R15**: Buff HP to 600. _REASON: the Conqueror should be beefier than the Quarrier, since the rank 15 is a leviathan/Conqueror (a combat ship, not a mining ship)._

**R12, R17 and R20**: make it so those ships get a x1.05 extra speed when cargo is full. _REASON: Those ships are already painfully slow, and they could be considered cargo ships, so they should be capable of carrying ore with no penalization._

**R17** should get 1 xp from each asteroid it mines, as well as getting 10 times the money for each ore. REASON: If not the ship is not profitable compared with killing ships. An example: 100000 Ore, around 140k $. With any ship from ranks 9-19 (specially ranks 12, 14, 16 and 18), you can get that money and xp in 5 minutes. 
**R19 and R20**: maybe make it so apart from the C-Slot active abiltiy, those ships would have an useful, extra passive ability.
Apart from that, **reduce price for techs** slightly (from 1024^current multiplier to **1000^current multiplier**).

**Shuttle** Goes base 1.00 thrust, .05 agility, 1 slot, always available from rank 5 (but not directly, only as a feature). 30 HP, 100 cargo, and it can use any tech minus Muon and Grav Bomb. Good ship to quickly get around, bad for combat, mining, or circling. 
When you pay for this option in shop (the price would be half the one for a life but it can only be paid once  in 24 hours (the max you can have of those at a time is 2)), next time your main ship is destroyed instead of dying you respawn 5 seconds after at 200 units from the place where your main ship was destroyed. Your ship will be returned to normal after you dock.

**Ship fusion**: When two or more ships press F button, the ships stay glued one to each other, sharing life and direction, but with individual control of each one's weapons.
The total HP would be the sum up of all the HP of each ship. 
Speed would be **[0.05+Σ(ShipSpeed*ShipLevel)]/Σ(ShipLevel)** because if, for example, a R15 and a R1 are fused, you cannot make an exact average of speed and agility since the engines of the R1 would overexert (it would be like an ant moving a baguette).
Agility would be calculated with **1/(Σ(1/A))** where A is the agility of each ship (so if you have 3 ships the formula would be 1/(1/A+1/B+1/C)  ).
The limit for fusion would be something like Σ(shiplevels)<=39 (so you can have as many ships fused as you want as long as they are above level 1 and the total level is below 39.

**Sensor overload**: this feature allows you to have twice your radar (and see planets and coins if your radar tech multiplied by 2 is bigger than 4.0) costing 15 lifepoints and 15 energy per second of use, with a cooldown of 5 seconds. All ships have this feature available, and not as a weapon or a slot. You just need to press R to do a deep scan and press R again to deactivate it. Be careful, because it can eventually destroy the ship! If radar is below the point to reach that 4.0, a bar below the radar that spikes if you get closer to a planet would appear.
_REASON: Planets are sometimes too difficult to find with slow ships, specially if you are under enemy fire. Also this feature has potential._

Maybe allow to **customize controls** (in the More Menu, replace the "Store" which doesn't exist, to "Customize Controls" or just made it a chat command, whatever you prefer). Apart from those add the **option to shoot laterally** by pressing Z or X.

As an extra **add a "Last Life!" Warning**.

For **human team, make radar updates by a rotating radius, in alien, update by an expanding circle.**
![imagen](https://user-images.githubusercontent.com/52273174/60272846-324fa280-98f5-11e9-8f3a-ed7890bf907a.png)
![imagen](https://user-images.githubusercontent.com/52273174/60272862-38458380-98f5-11e9-9dbe-1b91d00e01ea.png)
(Idea from Joyous18) From radar 2.1 **add the second closest object** (while still targeting the first). So you can see two ore, two enemy, two ally etc. Each extra 0.2 you add another arrow. At **2.3 radar could indicate size** too (asteroids with more ore are bigger and ships are their relative size on radar (R14 is small than R12 but bigger than R6, etc.).

From Joyous18 (later partially corrected code-wise by DamienVesper):
**Change GUEST to Cadet** and change the tutorial into a corrected version of this code (it seems way cooler and despite current tutorial is good people still ask us for this):

> 
> var tutorialCount = 0;
> var quest = 0;
> 
> function messageBox(a, b) {
>     let senderWrapper =  new Sender() //assume this is already defined
>     .setAuthor(tutorial)
>     .setMessage(b);
> }
> function readNextTutorial(a) {
>     if(tutorial == 0) {
>         messageBox(`${bt.user.username}`, `Hey there, cadet, welcome to the fight! Kinda small ship ya got there. Oh well, your first mission will be to bring our armada some much needed resources.`);
>         setTimeout(function() {
>             messageBox(`${bt.user.username}`, `Use your arrow keys or WASD to move. To mine, follow the Brown arrow and you'll find an ore asteroid. Press Space or click with your mouse to shoot it until it blows up to collect the ore.`);
>             quest = 1; //Mining quest for any ore
>             while(bt.user.currentOre < 1000) {
>                 let b = Math.floor(Math.random() * 10); //Just run code to avoid freezing browser.
>             }
>             return setTimeout(getNextTutorial, 2500);
>         }, 5000);
>     }
> Quest = 1;//special mining quest for any ore
> tutorial++;
> }
> 
> while(tutorial = 1) {
> if(ore > 1000) {//quest complete
> messageBox("Joyous18", "Thanks for your service. Now that you’ve got some extra Ore, bring it back to base so you can sell it.");
> 
> messageBox("Joyous18", "Follow the Grey arrow and you’ll get home. Then, press \‘x\’ to enter the station.");
> 
> Tutorial++;
> }
> }
> while(tutorial = 2) {
> if(enteredStation) {
> messageBox("Joyous18", "Right, ya gotta click \‘shop\’ and then sell your mined Ore for some cash. After that, press /’stats/’ and choose the radar upgrade.");//radar only upgrade clickable
> 
> Tutorial++;
> }
> }
> 
> while(tutorial = 3) {
> if(stats.radar > 1.0) {
> messageBox("Joyous18", "Haha, nice. Your ship’s a little better. Exit the station by pressin \’x\’ again to check it out.");
> 
> Tutorial++;
> }
> }
> 
> while(tutorial = 4) {
> if(stats.radar > 1.0) {
> messageBox("Joyous18", "Look at that! You’ve got a radar now. The " + team + “ dots are friendlies, “ + notTeam + “ are foe, and the other dots are Ore.”);
> 
> messageBox("Joyous18", "You’re ready to go, but a few more things: you can press the Down key to use your shield. Careful, it uses lots of energy. Q and E can be used to juke, and Shift is for drifting. Ya go a bit faster while drifting.”);
> 
> messageBox("Joyous18", "Last thing. Enter the station and save your progress. You only need a username and password to save so you can come back another day and explore the rest of the galaxy. Good Luck Cadet!”);
> Tutorial++;
> }
> }

**Comment by 2swap** [comment]
Some of this has already been implemented, and much of it is out of date/doesn't work anymore, like the miscellaneous ship buffs and nerfs. Cadet seems like a good idea. Please don't combine unrelated features into one issue- @tardisfromtornspace if you want to change to cadet, that's fine, but the rest of this doesn't seem to really be of much use anymore.
