### ISSUE TITLE
Idea for a boss

### ISSUE THREAD

**Issue by tardisfromtornspace** [TornDotSpace/Torn#198]
Perhaps make a green bot (yeah, that means that it can be killed by both teams), rank 15 (but different), armed with Muon, Hull nanobots, Spreadshot, Missile Swarm, Laser Beam, Energy Leech, Energy Disk, Ion Mine Beam, Cloak and Hyperdrive; but very, very slow and with almost no agility (0.15 thrust, 0.02 agility, 2500HP, 60000 cargo). It can spawn in any sector. When killed it gives 10,000 xp and 600,000 money.

**Comment by 2swap** [comment]
Why? This just seems like a random useless feature
