### ISSUE TITLE
Players can zoom out by holding control and scrolling the mouse wheel.  I attempted to fix it but didn't get anywhere. Ctrl+ and ctrl- already patched.

### ISSUE THREAD

**Issue by 2swap** [TornDotSpace/Torn#201]

**Comment by 2swap** [comment]
@chrisj1 Could you add that, if you already know how to do it?

Other than that, now that torn is open source this could be "hacked" so it's not top priority. Can be closed if you don't know how to fix.

**Comment by chrisj1** [comment]
I do not know. I think I might have looked that up before.

**Comment by DamienVesper** [comment]
Should be fixed in [4161f6a](https://github.com/TornDotSpace/Torn/tree/4161f6a2cfeebce10f860f2248cc1c89ea18ea99). If not, just leave it be. (A better option would be to not render anything past a certain player range at that point).
