### ISSUE TITLE
EMP locking controls

### ISSUE THREAD

**Issue by DamienVesper** [TornDotSpace/Torn#215]
When a player is EMP'd, all of their controls are effectively "locked" in place (keydown / keyup events are frozen). In reality, players should be immobilized, unable to shoot, and their shield should be disabled. Those are the only two things that should occur on EMP transmission, not what it is currently.

**Comment by DamienVesper** [comment]
@tardisfromtornspace @johnnyapol

**Comment by DamienVesper** [comment]
This is also being fixed in my fork, just put it here for clarity.

**Comment by tardisfromtornspace** [comment]
Just so you know 2swap asked for changing the EMP effect to a weapons jammer effect, The real bug is having the controls locked, it's only suppsoed to discharge weapons and lower shields.

**Comment by tardisfromtornspace** [comment]
We have the old code that immbilizes, amkes them unable to shoot and lowers shields, but that's not 2swap wanted for balancing teh EMP. nevertheless, here you are:

		this.empTimer = t;

		//turn off all keys
		this.w = this.e = this.a = this.s = this.d = this.c = this.space = false;
		if (!this.isBot) this.emit('emp', { t: t });

**Comment by tardisfromtornspace** [comment]
Ok I've just fixed it so it does the discharge part for players, and the immoblizing and lowering shields for bots (consider it as the bot brain short-circuiting)

    this.charge += -t*this.energy2; // Emp jams the ship. multiplying by energy2 ensures that regardless of energy tech, you remain jammed the same time
    if (this.isBot) {
      this.empTimer += t; // Adding a condition, checking that this doesn't cause the EMP bug.
      this.w = this.e = this.a = this.s = this.d = this.c = this.space = false; // Bot brains will seem to short-circuit due to the EMP
    }

**Comment by DamienVesper** [comment]
Resolved in [0d57c9b](https://github.com/TornDotSpace/Torn/commit/0d57c9bf0f29709a6073b14ded709ac35849ee0a).
