### ISSUE TITLE
Black hole achievement problem (and possible solution!)

### ISSUE THREAD

**Issue by CMDR-JohnAlex** [TornDotSpace/Torn#327]
Because I want the last few achievements, I know that I have to crash into a black hole for the blue and white yet when I do crash it sometimes shows that I crashed and got an achievement and sometimes it doesn't. When I reload the tab after docking it removes the black hole achievements and I don't get my trails, I have purposefully died MANY TIMES losing lots of money and exp get to try and get this achievement.

Is there some way you can fix this?
![image](https://user-images.githubusercontent.com/83140435/120908371-a34a7980-c637-11eb-8ad5-310545e6bd11.png)

While I am not a javascript developer and haven't looked at the code, I THINK the problem is that when you crash, it gives you the achievement, then to save your achievement you have to dock but then you die from the black hole, if you could give the achievement after a few seconds, the player could respawn quickly and get the achievement and dock to save it.

**Comment by A2Broslol** [comment]
So basically delay granting the achievement till the player docks and then give it.

**Comment by johnnyapol** [comment]
Achievements are supposed to be saved on death and docking so something else is wrong here.

**Comment by 2swap** [comment]
This is fixed on master as far as I know
