### ISSUE TITLE
Torn store success page

### ISSUE THREAD

**Issue by A2Broslol** [TornDotSpace/Torn#328]
After I purchased MVP rank I was directed to a page similar to this:(Picture is from torn.space/fun)
![404 Not Found](https://user-images.githubusercontent.com/85319606/120911002-72773e00-c651-11eb-8647-ac38636e2bf6.png)

**Comment by DESTANK72** [comment]
what did the page say

**Comment by 2swap** [comment]
We should automate this to give people the rank they buy, the old success page is a pain

**Comment by johnnyapol** [comment]
we need to look into this from stripe's end. im assuming they have the ability to do dummy transactions to test it.
