### ISSUE TITLE
Missing background

### ISSUE THREAD

**Issue by A2Broslol** [TornDotSpace/Torn#329]
Missing backgrounds in torn.space/leaderboard, torn.space/credits, torn.space/store etc
Example:
![Credits](https://user-images.githubusercontent.com/85319606/120911160-d2221900-c652-11eb-9feb-c77b92856961.png)

**Comment by A2Broslol** [comment]
I'm not sure if this is clientside or server.

**Comment by johnnyapol** [comment]
This has been fixed in master for some time but the branch currently isn't stable enough to deploy
