### ISSUE TITLE
Disappearing Background

### ISSUE THREAD

**Issue by Ann1h1lator** [TornDotSpace/Torn#352]
Pressing any key while docked or undocked but on a different computer tab will lead to the star background disappearing for one second. No idea why this happens, and its not a big deal, but should be fixed

![Screenshot 2021-06-13 7 33 58 AM](https://user-images.githubusercontent.com/85811829/121805599-daadbd00-cc19-11eb-8ba1-700eba591520.png)

**Comment by TheGoldenRetriever** [comment]
Oh

**Comment by DamienVesper** [comment]
Tested on multiple clients, can't reproduce. This is probably an issue specific to your device, or has already been resolved. If the issue still persists, feel free to reopen.
