### ISSUE TITLE
Anything containing turdis in any way breaks the test server

### ISSUE THREAD

**Issue by tardisfromtornspace** [TornDotSpace/Torn#354]
Annihilator and I were playing, when I tried to register as turdis. That broke the server. After experimenting, anything containing turdis, some permutations of it, as well as t u r d i s  with the spaces replaced by random character strings break the server too, as wel as moving the words one to the left (uvsejt, for example)

**Comment by DamienVesper** [comment]
Could you show some examples? I don't know how to reproduce.

**Comment by tardisfromtornspace** [comment]
Go to test.torn.space, then create an account like thegreatturdis or turdis23.

**Comment by johnnyapol** [comment]
Fixed by https://github.com/TornDotSpace/Torn/commit/1ad88de518d1a5e53785421dd659272ddc0c571b

**Comment by A2Broslol** [comment]
The world deserves to know what was going on backstage to let _this_ happen
