### ISSUE TITLE
Switching chat tabs doesn't update properly

### ISSUE THREAD

**Issue by 2swap** [TornDotSpace/Torn#369]
the chat box is so bugged
✨DαɱιҽɳVҽʂρҽɾ✨ — Today at 3:00 PM
wdym
recognizer — Today at 3:00 PM
click team chat then global chat again
it just vanishes
✨DαɱιҽɳVҽʂρҽɾ✨ — Today at 3:00 PM
huh thats interesting
recognizer — Today at 3:02 PM
~~also newlining long messages seems to occur inconsistently~~ (Resolved).

**Comment by 2swap** [comment]
it also sometimes just doesn't update when it should

**Comment by DamienVesper** [comment]
If you switch from a chat room to another, it will not update the chat until you have selected another room (essentially lagging behind by one action).
