### ISSUE TITLE
Login page buttons are ugly

### ISSUE THREAD

**Issue by 2swap** [TornDotSpace/Torn#370]
Make them translucent rounded rectangles?

**Comment by DamienVesper** [comment]
Possibly so. Should probably add a minimum width on them too, as they look decently odd on smaller screens.

**Comment by DamienVesper** [comment]
Ultrawide monitors will also have some degree of distortion, but whether that looks bad is up to you, which in that case, I would just set the width to a fixed amount instead of relative to container width.
