### ISSUE TITLE
Internal Server error, unable to connect to database

### ISSUE THREAD

**Issue by tardisfromtornspace** [TornDotSpace/Torn#821]
Apparently now people on production cannot use any account to play the game, it throws an Internal Server Error a "failed to connect to Torn Account Services", and trying to create a new account throws an internal server error.
![imagen](https://github.com/TornDotSpace/Torn/assets/52273174/841b0ce7-e2a4-469b-8dd0-b9ef32b19026)

**Comment by 2swap** [comment]
Poked around on the server. It's been running for over a year... what could have suddenly gone wrong?

Answer: Torn log files since Jan 1 2021 completely filled up the server's hard disk. lol.

**Comment by 2swap** [comment]
![logslogslogslogslogs](https://github.com/TornDotSpace/Torn/assets/16504868/36efb3f5-74ae-4f3f-8bfd-aa57bdb27117)

**Comment by 2swap** [comment]
Fixed
