### ISSUE TITLE
Zalgo filter (or something related to it) causes players to crash due to internal server error

### ISSUE THREAD

**Issue by tardisfromtornspace** [TornDotSpace/Torn#99]
I've decided to comment the lines from "Zalgo" filter update until this problem is solved.

**Comment by DamienVesper** [comment]
Can you link the commit for this? I have an idea of what might be causing it, but I need to know when and where it was changed.

**Comment by 2swap** [comment]
Was this fixed? Seems there's no more zalgo.

**Comment by DamienVesper** [comment]
Already fixed.
